### ISSUE TITLE
Replace deprecated `rtm.start` with `rtm.connect`

### ISSUE THREAD

**Issue by szymon-jez** [socialpaymentsbv/slack_autolinker#12]
Details:

1. https://api.slack.com/changelog/2021-10-rtm-start-to-stop
2. https://api.slack.com/methods/rtm.start

**Comment by vruizext** [comment]
Upgrading to the latest version of the `elixir-slack` client should solve the issue, the call to `rtm-connect` is done in this library and has been replaced with `rtm-start` in the last version

https://github.com/BlakeWilliams/Elixir-Slack

**Comment by szymon-jez** [comment]
@pootsbook I have upgraded to the newest `elixir-slack` in https://github.com/socialpaymentsbv/slack_autolinker/tree/sj/upgrade. Could you check if the app/bot in Slack is configured fine? 

![Screenshot 2022-10-11 at 15 01 19](https://user-images.githubusercontent.com/35540/195097849-e88f9dd0-b64f-43e0-a46a-4181b9db2f19.png)
